// Mock expense data matching Supabase structure
export const initialExpenses = [
  {
    id: '1',
    amount: 90,
    description: 'Crypto buy',
    date: '2026-02-21',
    category: 'investing',
    subcategory: 'crypto',
    user_id: 'mock-user',
    created_at: '2026-02-21T17:30:00Z',
  },
  {
    id: '2',
    amount: 35,
    description: 'Food delivery',
    date: '2026-02-20',
    category: 'wants',
    subcategory: 'food_delivery',
    user_id: 'mock-user',
    created_at: '2026-02-20T12:30:00Z',
  },
  {
    id: '3',
    amount: 45,
    description: 'Groceries',
    date: '2026-02-19',
    category: 'needs',
    subcategory: 'groceries',
    user_id: 'mock-user',
    created_at: '2026-02-19T11:30:00Z',
  },
  {
    id: '4',
    amount: 120,
    description: 'Rent payment',
    date: '2026-02-18',
    category: 'needs',
    subcategory: 'rent',
    user_id: 'mock-user',
    created_at: '2026-02-18T09:00:00Z',
  },
  {
    id: '5',
    amount: 65,
    description: 'Dinner out',
    date: '2026-02-17',
    category: 'wants',
    subcategory: 'dining_out',
    user_id: 'mock-user',
    created_at: '2026-02-17T19:30:00Z',
  },
  {
    id: '6',
    amount: 250,
    description: 'Stock purchase',
    date: '2026-02-16',
    category: 'investing',
    subcategory: 'stocks',
    user_id: 'mock-user',
    created_at: '2026-02-16T10:00:00Z',
  },
  {
    id: '7',
    amount: 42,
    description: 'Utilities bill',
    date: '2026-02-15',
    category: 'needs',
    subcategory: 'utilities',
    user_id: 'mock-user',
    created_at: '2026-02-15T14:00:00Z',
  },
  {
    id: '8',
    amount: 85,
    description: 'Shopping',
    date: '2026-02-14',
    category: 'wants',
    subcategory: 'shopping',
    user_id: 'mock-user',
    created_at: '2026-02-14T16:45:00Z',
  },
  {
    id: '9',
    amount: 500,
    description: 'Mutual funds SIP',
    date: '2026-02-13',
    category: 'investing',
    subcategory: 'mutual_funds',
    user_id: 'mock-user',
    created_at: '2026-02-13T08:00:00Z',
  },
  {
    id: '10',
    amount: 55,
    description: 'Transport',
    date: '2026-02-12',
    category: 'needs',
    subcategory: 'transport',
    user_id: 'mock-user',
    created_at: '2026-02-12T18:30:00Z',
  },
  {
    id: '11',
    amount: 28,
    description: 'Coffee',
    date: '2026-02-11',
    category: 'wants',
    subcategory: 'dining_out',
    user_id: 'mock-user',
    created_at: '2026-02-11T10:15:00Z',
  },
  {
    id: '12',
    amount: 95,
    description: 'Streaming services',
    date: '2026-02-10',
    category: 'wants',
    subcategory: 'streaming',
    user_id: 'mock-user',
    created_at: '2026-02-10T12:00:00Z',
  },
];

// Canned responses for chat
export const chatResponses: Record<string, string> = {
  "hello": "Hello! I'm your Finesse financial assistant. How can I help you today?",
  "hi": "Hi there! I'm your Finesse financial assistant. How can I help with your finances today?",
  "help": "I can help you with budgeting tips, investment advice, and expense categorization. Just ask me a specific question!",
  "budget": "Creating a budget is essential! Start by tracking your expenses in the Home tab, then use the 50/30/20 rule: 50% for needs, 30% for wants, and 20% for savings and investments.",
  "investing": "For beginners, I recommend starting with low-cost index funds. They provide diversification and typically have lower fees than actively managed funds.",
  "save money": "To save money, try the 24-hour rule for non-essential purchases, meal prep to reduce food costs, and review your subscriptions regularly to cut unused services.",
  "debt": "To tackle debt effectively, consider the avalanche method (paying highest interest first) or the snowball method (paying smallest balances first for psychological wins).",
  "credit score": "To improve your credit score: pay bills on time, keep credit utilization under 30%, don't close old accounts, limit new credit applications, and regularly check your credit report.",
  "retirement": "For retirement planning, take advantage of employer 401(k) matching, consider opening a Roth IRA, and aim to save at least 15% of your income for retirement.",
  "emergency fund": "An emergency fund should cover 3-6 months of essential expenses. Keep it in a high-yield savings account for easy access and some interest growth.",
  "stock market": "The stock market has historically returned about 10% annually before inflation. For most people, investing in broad market index funds is the smartest approach.",
  "crypto": "Cryptocurrency is highly volatile. Only invest money you can afford to lose, and keep it as a small percentage of your overall portfolio (5-10% maximum for most investors).",
  "housing": "When buying a home, the 28/36 rule is helpful: spend no more than 28% of gross income on housing costs and no more than 36% on total debt.",
  "insurance": "Everyone should have health insurance, auto insurance (if you drive), renters/homeowners insurance, and consider disability and life insurance if you have dependents.",
};

// Initial chat messages
export const initialMessages = [
  {
    id: '1',
    text: "Welcome to Finesse! I'm your AI financial assistant. How can I help you today?",
    sender: 'bot',
    timestamp: new Date().getTime() - 1000 * 60 * 5, // 5 minutes ago
  },
];
